name: CI

on:
  push:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: appditto/libvips:latest
    steps:
    - name: Check out code
      uses: actions/checkout@master

    - name: Run Tests
      run: |
        cd server
        go test ./...

  build_and_publish_go:
    name: Build and Publish GO Image
    needs: test
    runs-on: ubuntu-latest
    env:
      GITHUB_RUN_ID: ${{ github.run_id }}
    steps:
      - uses: actions/checkout@master
      - name: Login to registry
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get branch name (merge)
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

      - name: Get branch name (pull request)
        if: github.event_name == 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV

      - name: Build and tag
        if: success()
        run: docker build -t pawr/pawnimals-server:${{ env.BRANCH_NAME }}-${{ env.GITHUB_RUN_ID }} server

      - name: Push image
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push pawr/pawnimals-server:${{ env.BRANCH_NAME }}-${{ env.GITHUB_RUN_ID }}
